spring:
  datasource:
    url: jdbc:sqlserver://123.125.12.107:1433;DatabaseName=peis_qa
    username: sa
    password: Tphy@123.
  sqlserver:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver



mybatis-plus:
  type-aliases-package: tphy.peis.entity
  mapper-locations: /mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    cache-enabled: true
    default-statement-timeout: 30
    default-fetch-size: 10000
    map-underscore-to-camel-case: false
# 日志等级
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: debug
    com.baomidou.mybatisplus: debug
    com.dragonsoft.demojar.mapper: debug
server:
  port: 8090
